<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class ClientPasswordReset extends Notification
{
    use Queueable;

    /**
     * The new password generated by admin
     *
     * @var string
     */
    public $password;

    /**
     * Create a new notification instance.
     */
    public function __construct(string $password)
    {
        $this->password = $password;
    }

    /**
     * Get the notification's delivery channels.
     *
     * @return array<int, string>
     */
    public function via(object $notifiable): array
    {
        return ['mail'];
    }

    /**
     * Get the mail representation of the notification.
     */
    public function toMail(object $notifiable): MailMessage
    {
        return (new MailMessage)
            ->subject('Nueva Contraseña - CH Logistic')
            ->greeting('¡Hola ' . $notifiable->name . '!')
            ->line('Un administrador ha restablecido tu contraseña de acceso.')
            ->line('Tu nueva contraseña es:')
            ->line('**' . $this->password . '**')
            ->line('Por tu seguridad, te recomendamos cambiar esta contraseña después de iniciar sesión.')
            ->action('Iniciar Sesión', url('/login'))
            ->line('Si no solicitaste este cambio, por favor contacta con el administrador inmediatamente.')
            ->salutation('Saludos, Equipo CH Logistic');
    }

    /**
     * Get the array representation of the notification.
     *
     * @return array<string, mixed>
     */
    public function toArray(object $notifiable): array
    {
        return [
            //
        ];
    }
}
